# Change these first
owner: m4d3bug # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://blog.madebug.net
    expectedStatusCodes:
      - 200
  - name: LB-01
    url: https://lb-01.m4d3bug.com
    expectedStatusCodes:
      - 403
  - name: LB-02
    url: https://lb-01.m4d3bug.com
    expectedStatusCodes:
      - 200
  - name: Whoogle
    url: https://whoogle.madebug.net
    expectedStatusCodes:
      - 200
  - name: Google DNS 
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.madebug.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
